name: MLOps Pipeline

on:
  push:
    branches:
      - main

jobs:

  # Step 1: Data Preprocessing
  preprocess-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Preprocess data
        run: |
          python preprocess.py  

  # Step 2: Model Training and Evaluation
  train-model:
    runs-on: ubuntu-latest
    needs: preprocess-data
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train model
        run: |
          python train.py  # Replace with your training script

      - name: Save trained model
        run: |
          mkdir -p models
          cp trained_model.pkl models/  # Replace with the actual path to your model file

      - name: Upload Model Artifact
        uses: actions/upload-artifact@v2
        with:
          name: trained_model
          path: models/

  # Step 3: Docker Build and Push

  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        env:
          REPOSITORY: fastapi
          IMAGE_TAG: tpAchat
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/$REPOSITORY:$IMAGE_TAG .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/$REPOSITORY:$IMAGE_TAG
